name: PHPUnit

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    name: PHP ${{ matrix.php-versions }} Unit Tests

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@2.13.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, pecl, phpunit
          extensions: intl, json, mbstring, xdebug, xml
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3.0.9
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Enable Tachycardia
        run: echo "TACHYCARDIA_MONITOR_GA=enabled" >> $GITHUB_ENV

      - name: Test with PHPUnit
        run: vendor/bin/phpunit --verbose --coverage-text
        env:
          TERM: xterm-256color

      - if: matrix.php-versions == '8.0'
        name: Run Coveralls
        run: vendor/bin/php-coveralls --verbose --coverage_clover=build/phpunit/clover.xml --json_path build/phpunit/coveralls-upload.json
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php-versions }}

  coveralls:
    needs: [main]
    name: Coveralls Finished
    runs-on: ubuntu-latest
    steps:
      - name: Upload Coveralls results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
